import type { Metadata } from "next";
import { Geist, Geist_Mono, Quicksand } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const quicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Navigation() {
  return (
    <nav className="w-full p-6 flex flex-wrap items-center gap-x-2">
      {/* logo */}
      <h1 className="text-3xl sm:text-2xl font-bold font-[family-name:var(--font-quicksand)] flex gap-x-2">
        <Image
          className="dark:invert"
          src="/cardano-ada-logo.svg"
          alt="Cardano logo"
          width={30}
          height={30}
          priority
        />
        <span>Cardano Tools</span>
      </h1>

      {/* navigation */}
      <button className="btn btn-ghost">browse</button>
      <button className="btn btn-ghost">mint</button>
      <button className="btn btn-ghost">burn</button>
      <button className="btn btn-ghost">Register</button>
      <button className="btn btn-ghost">Royalities</button>
      <button className="btn btn-ghost">Dropper</button>
      <button className="btn btn-ghost">My NFTs</button>
      <button className="btn btn-ghost">My Wallet</button>
      <button className="btn btn-ghost">[CHIEN]-Pool</button>
    </nav>
  );
}

function FIrstTry(props) {
  return (
    <div className="min-h-screen grid grid-rows-[auto_1fr_auto_auto] justify-items-center">
      {/* header */}
      <header className="w-full max-w-screen-xl">
        <Navigation></Navigation>
      </header>

      {/* main content */}
      <main className="flex flex-col gap-8 items-center sm:items-start w-full px-10  max-w-screen-xl">
        {props.children}
      </main>

      {/* divider */}
      <div className="divider w-full "></div>

      {/* footer */}
      <footer className="footer justify-center items-center max-w-screen-xl pb-4">
        <a className="link link-hover">Branding</a>
        <a className="link link-hover">Design</a>
        <a className="link link-hover">Marketing</a>
        <a className="link link-hover">Advertisement</a>
      </footer>
    </div>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${quicksand.variable} antialiased`}
      >
        {/* <FIrstTry>{children}</FIrstTry> */}

        <div className="drawer lg:drawer-open">
          <input id="my-drawer-2" type="checkbox" className="drawer-toggle" />
          <div className="drawer-content flex flex-col items-center justify-center">
            {/* Page content here */}
            <label
              htmlFor="my-drawer-2"
              className="btn btn-primary drawer-button lg:hidden"
            >
              Open drawer
            </label>
          </div>
          <div className="drawer-side">
            {/* backdrop for open drawer on mobile */}
            <label
              htmlFor="my-drawer-2"
              aria-label="close sidebar"
              className="drawer-overlay"
            ></label>

            {/* Sidebar content */}
            <ul className="menu bg-base-200 text-base-content min-h-full w-80">
              {/* Sidebar header */}
              <h1 className="text-3xl font-bold font-[family-name:var(--font-quicksand)] flex gap-x-2 pl-4 pt-4 pb-36">
                <Image
                  className="invert"
                  src="/cardano-ada-logo.svg"
                  alt="Cardano logo"
                  width={40}
                  height={40}
                  priority
                />
                <span>Cardano Tools</span>
              </h1>

              {/* Sidebar items */}
              <li>
                <a>Sidebar Item 1</a>
              </li>
              <li>
                <a>Sidebar Item 2</a>
              </li>
            </ul>
          </div>
        </div>
      </body>
    </html>
  );
}
